# Generated by Django 3.0 on 2020-11-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance_kms', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='sample description', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='distance_kms',
            field=models.DecimalField(decimal_places=2, default=12.6, max_digits=5),
            preserve_default=False,
        ),
    ]
